/******************************

温馨提示：资源来自全网搜集，如有侵权及时与我方联系：w6666999@gmail.com
脚本功能：屏蔽如下APP开屏广告 
下载地址：苹果商店搜索下载APP
更新时间：2023-03-04
微信公众号：夕阳技术线报
资源论坛：www.laosu.xyz
资源网盘：http://zy.laosu.xyz
TG交流群：hhttps://t.me/xyjsxb
TG订阅：https://t.me/S666699999
使用声明：此脚本仅供学习与交流，请勿转载与贩卖！??????

*******************************

[rewrite_local]

#广汽传祺屏蔽开屏广告
^https?:\/\/gsp\.gacmotor\.com\/gateway\/webapi\/baseinfo\/advertise\/getAdvertiseByPositionCode?positionCode*




hostname = api.bspapp.com,api-access.pangolin-sdk-toutiao.com,api.cloud.189.cn,piq.in-neo.cn,kjp.cupid.iqiyi.com,afd.baidu.com,adse.ximalaya.com,adproxy.autohome.com.cn,*.i4.*,mapiv5.caixin.com,ap.dongqiudi.com,syh.zybang.com,sdk.pairmb.com,vip7.fzwdyy.cn,app.dewu.com,rtbapi.douyucdb.cn,m5.amap.com,adapi.izuiyou.com,kad.gotokeep.com,appconf.mail.163.com,api.m.jd.com,adx.yiche.com,setting.huajiao.com,image.huajiao.com,mob.mddcloud.com.cn,appwk.baidu.com,api.tipsoon.com,ad.12306.cn,api.zhihu.com,nex.163.com,*.gdt.qq.com,open.e.kuaishou.com,*.rili.*,*.etouch.cn,sdk.alibaba.com.ailbaba.me,pipi.4kya.com,pzoap.moedot.net, js-ad.ayximgss.com,103.91.210.141:2515,dd-static.jd.com,m.ctrip.com,myip.ipip.net,googleads.g.doubleclick.net,*music.163*,*music.126*,ms.jr.jd.com,acs.m.taobao.com,qde.qunar.com,apps.api.ke.com,api.yonghuivip.com,client.app.coc.10086.cn,wap.bank.ecitic.com,api.ahmobile.cn,creditcardapp.bankcomm.cn,api.kkmh.com,adx-cn.anythinktech.com,static.95508.com,app.zhuanzhuan.com,scxs.pysmei.com,sdk.qzbonline.com,*.360buyimg.com,ilce.alicdn.com,api.jtshuzhiwa.com,api.czbt.cc,top-widgets-api.xiaozujian.com,api.vistopia.com.cn,*.kuaidi100.com,gw.csdn.net,m.creditcard.ecitic.com,y.gtimg.cn,adm.10jqka.com.cn,i.ys7.com,im-x.jd.com,magev*.if.qidian.com,gw.aihuishou.com,wxsnsdythumb.wxs.qq.com,kepler.jd.com,mlol.qt.qq.com,api.shizhongruyi.com,api.caiyunapp.com,ssp.soulapp.cn
,api3.cls.cn,b2baifanfan.baidu.com,rich.kuwo.cn


**********************************************/